"""Add preferred_faculty_id and preferred_program_id to User model

Revision ID: 3c09d1b9aa1d
Revises: c16f68f9af03
Create Date: 2025-08-24 14:32:21.624900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c09d1b9aa1d'
down_revision: Union[str, Sequence[str], None] = 'c16f68f9af03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_faculty_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('preferred_program_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'programs', ['preferred_program_id'], ['id'])
    op.create_foreign_key(None, 'users', 'faculties', ['preferred_faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'preferred_program_id')
    op.drop_column('users', 'preferred_faculty_id')
    # ### end Alembic commands ###
