"""Add full schema for adaptive learning system

Revision ID: 45eab53f22cc
Revises: 4bd039fb843b
Create Date: 2025-08-23 18:12:21.430016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45eab53f22cc'
down_revision: Union[str, Sequence[str], None] = '4bd039fb843b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('was_weakness', sa.Boolean(), nullable=True),
    sa.Column('was_srs', sa.Boolean(), nullable=True),
    sa.Column('was_new', sa.Boolean(), nullable=True),
    sa.Column('is_first_attempt', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('questions', sa.Column('total_attempts', sa.Integer(), nullable=True))
    op.execute("UPDATE questions SET total_attempts = 0 WHERE total_attempts IS NULL")
    op.alter_column('questions', 'total_attempts', existing_type=sa.Integer(), nullable=False)
    op.add_column('questions', sa.Column('total_incorrect', sa.Integer(), nullable=True))
    op.execute("UPDATE questions SET total_incorrect = 0 WHERE total_incorrect IS NULL")
    op.alter_column('questions', 'total_incorrect', existing_type=sa.Integer(), nullable=False)
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('quiz_session_questions', sa.Column('order_number', sa.Integer(), nullable=True))
    op.execute("UPDATE quiz_session_questions SET order_number = 0 WHERE order_number IS NULL") # Assuming 0 as default
    op.alter_column('quiz_session_questions', 'order_number', existing_type=sa.Integer(), nullable=False)
    op.add_column('quiz_session_questions', sa.Column('user_answer', sa.String(), nullable=True))
    op.add_column('quiz_session_questions', sa.Column('is_correct', sa.Boolean(), nullable=True))
    op.add_column('quiz_session_questions', sa.Column('answered_at', sa.DateTime(), nullable=True))
    op.add_column('quiz_session_questions', sa.Column('time_taken', sa.Integer(), nullable=True))
    op.add_column('quiz_session_questions', sa.Column('selection_reason', sa.String(length=50), nullable=True))
    op.add_column('quiz_session_questions', sa.Column('selection_score', sa.Float(), nullable=True))
    op.add_column('quiz_sessions', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('quiz_sessions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('quiz_sessions', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE quiz_sessions SET is_completed = FALSE WHERE is_completed IS NULL")
    op.alter_column('quiz_sessions', 'is_completed', existing_type=sa.Boolean(), nullable=False)
    op.add_column('quiz_sessions', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.execute("UPDATE quiz_sessions SET total_questions = 0 WHERE total_questions IS NULL") # Assuming 0 as default
    op.alter_column('quiz_sessions', 'total_questions', existing_type=sa.Integer(), nullable=False)
    op.add_column('quiz_sessions', sa.Column('final_score', sa.Float(), nullable=True))
    op.drop_column('quiz_sessions', 'is_active')
    op.drop_column('quiz_sessions', 'correct_answers')
    op.drop_column('quiz_sessions', 'questions_count')
    op.drop_column('quiz_sessions', 'created_at')
    op.add_column('user_answers', sa.Column('correct_streak', sa.Integer(), nullable=True))
    op.execute("UPDATE user_answers SET correct_streak = 0 WHERE correct_streak IS NULL")
    op.alter_column('user_answers', 'correct_streak', existing_type=sa.Integer(), nullable=False)
    op.add_column('user_answers', sa.Column('next_review_date', sa.DateTime(), nullable=True))
    op.add_column('user_answers', sa.Column('time_taken', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'time_taken')
    op.drop_column('user_answers', 'next_review_date')
    op.drop_column('user_answers', 'correct_streak')
    op.add_column('quiz_sessions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('quiz_sessions', sa.Column('questions_count', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    op.add_column('quiz_sessions', sa.Column('correct_answers', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('quiz_sessions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('quiz_sessions', 'final_score')
    op.drop_column('quiz_sessions', 'total_questions')
    op.drop_column('quiz_sessions', 'is_completed')
    op.drop_column('quiz_sessions', 'completed_at')
    op.drop_column('quiz_sessions', 'started_at')
    op.drop_column('quiz_session_questions', 'selection_score')
    op.drop_column('quiz_session_questions', 'selection_reason')
    op.drop_column('quiz_session_questions', 'time_taken')
    op.drop_column('quiz_session_questions', 'answered_at')
    op.drop_column('quiz_session_questions', 'is_correct')
    op.drop_column('quiz_session_questions', 'user_answer')
    op.drop_column('quiz_session_questions', 'order_number')
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('questions', 'total_incorrect')
    op.drop_column('questions', 'total_attempts')
    
    op.drop_table('interaction_logs')
    # ### end Alembic commands ###