"""upgrade_schema_for_feedback_and_reporting

Revision ID: 46c04043db9e
Revises: e1f3f3e3d3a0
Create Date: 2025-08-31 13:07:33.351686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c04043db9e'
down_revision: Union[str, Sequence[str], None] = 'e1f3f3e3d3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_course_program_association', 'course_program_association', type_='primary')
    op.alter_column('course_program_association', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course_program_association', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('feedback', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'questions', ['question_id'], ['id'])
    op.create_primary_key('pk_course_program_association', 'course_program_association', ['course_id', 'program_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_course_program_association', 'course_program_association', type_='primary')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'question_id')
    op.alter_column('course_program_association', 'program_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_program_association', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_primary_key('pk_course_program_association', 'course_program_association', ['course_id', 'program_id'])
    # ### end Alembic commands ###
