"""Add to_dict method to Question model

Revision ID: 5212c9e7ff46
Revises: 7987dfc1bf48
Create Date: 2025-08-24 15:17:21.572010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5212c9e7ff46'
down_revision: Union[str, Sequence[str], None] = '7987dfc1bf48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
