
"""Add interaction logging and question analytics

Revision ID: af1582f36697
Revises: 45eab53f22cc
Create Date: 2025-08-24 08:45:43.013162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1582f36697'
down_revision: Union[str, Sequence[str], None] = '45eab53f22cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_table('interaction_logs',
#    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#    sa.Column('user_id', sa.Integer(), nullable=False),
#    sa.Column('question_id', sa.Integer(), nullable=False),
#    sa.Column('session_id', sa.Integer(), nullable=False),
#    sa.Column('is_correct', sa.Boolean(), nullable=False),
#    sa.Column('time_taken', sa.Integer(), nullable=False),
#    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
#    sa.Column('attempt_number', sa.Integer(), nullable=False),
#    sa.Column('was_weakness', sa.Boolean(), nullable=True),
#    sa.Column('was_srs', sa.Boolean(), nullable=True),
#    sa.Column('was_new', sa.Boolean(), nullable=True),
#    sa.Column('is_first_attempt', sa.Boolean(), nullable=True),
#    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
#    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ),
#    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
#    sa.PrimaryKeyConstraint('id')
#    )
#    op.add_column('questions', sa.Column('total_attempts', sa.Integer(), nullable=False, server_default='0'))
#    op.add_column('questions', sa.Column('total_incorrect', sa.Integer(), nullable=False, server_default='0'))
#    op.add_column('quiz_session_questions', sa.Column('selection_reason', sa.String(length=50), nullable=True))
#    op.add_column('quiz_session_questions', sa.Column('selection_score', sa.Float(), nullable=True))
	pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_column('quiz_session_questions', 'selection_score')
#    op.drop_column('quiz_session_questions', 'selection_reason')
#    op.drop_column('questions', 'total_incorrect')
#    op.drop_column('questions', 'total_attempts')
#    op.drop_table('interaction_logs')
	pass 
   # ### end Alembic commands ###

