"""Add is_reported column to QuizSessionQuestion

Revision ID: 10f5785b27d7
Revises: 72f9ead47eec
Create Date: 2025-08-28 16:36:45.243044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f5785b27d7'
down_revision: Union[str, Sequence[str], None] = '72f9ead47eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_session_questions', sa.Column('is_reported', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_session_questions', 'is_reported')
    # ### end Alembic commands ###
