"""Add has_latex, difficulty_score, and explanation_image_url to Question model

Revision ID: 4bd039fb843b
Revises: bac0da5bfa2f
Create Date: 2025-08-23 08:45:22.791145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd039fb843b'
down_revision: Union[str, Sequence[str], None] = 'bac0da5bfa2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('has_latex', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('questions', sa.Column('difficulty_score', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('explanation_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'explanation_image_url')
    op.drop_column('questions', 'difficulty_score')
    op.drop_column('questions', 'has_latex')
    # ### end Alembic commands ###
