"""Add course relationship to QuizSession model

Revision ID: 7987dfc1bf48
Revises: 3c09d1b9aa1d
Create Date: 2025-08-24 15:06:02.062769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7987dfc1bf48'
down_revision: Union[str, Sequence[str], None] = '3c09d1b9aa1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
