"""add_min_max_difficulty_to_course

Revision ID: af8b7bff5938
Revises: 13ad0788bca1
Create Date: 2025-08-30 05:04:39.151487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8b7bff5938'
down_revision: Union[str, Sequence[str], None] = '13ad0788bca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('min_difficulty', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('max_difficulty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'max_difficulty')
    op.drop_column('courses', 'min_difficulty')
    # ### end Alembic commands ###
