"""Add image_url to Question model

Revision ID: bac0da5bfa2f
Revises: 4ea05a643ed7
Create Date: 2025-08-19 16:26:33.497701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac0da5bfa2f'
down_revision: Union[str, Sequence[str], None] = '4ea05a643ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'image_url')
    # ### end Alembic commands ###
