"""Add options and correct_answer to Question model

Revision ID: bfbb013f636e
Revises: c4e391ed18e5
Create Date: 2025-08-17 15:32:31.744502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfbb013f636e'
down_revision: Union[str, Sequence[str], None] = 'c4e391ed18e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.add_column('questions', sa.Column('correct_answer', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'options')
    # ### end Alembic commands ###
