"""Add selection_metadata to QuizSessionQuestion and initial_user_skill_level to QuizSession

Revision ID: cb57614785ec
Revises: af8b7bff5938
Create Date: 2025-08-30 21:18:31.238039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb57614785ec'
down_revision: Union[str, Sequence[str], None] = 'af8b7bff5938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_session_questions', sa.Column('selection_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('quiz_session_questions', 'is_reported',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('quiz_sessions', sa.Column('initial_user_skill_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'initial_user_skill_level')
    op.alter_column('quiz_session_questions', 'is_reported',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('quiz_session_questions', 'selection_metadata')
    # ### end Alembic commands ###
